version: "3.8"
services:
  viz:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:8080
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  api:
    image: ghcr.io/agmcc/csc8499/go-server
    ports:
      - 5688:5688/udp
    environment:
      HOST: "{{.Node.Hostname}}"
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '1'
          memory: 250M
      placement:
        constraints:
            - "node.role==worker"
            - "node.labels.priority!=3"
        # Will be added dynamically (Note: Seem to need to use reverse order?)
        preferences:
         - spread: node.labels.p1

