datasources:
- name: Prometheus
  type: prometheus
  type_name: Prometheus
  type_logo_url: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  access: proxy
  url: "http://prometheus:9090"
  org_id: 1
  is_default: true
  read_only: false
