apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-conf
  namespace: monitoring
data:
  datasources.yml: |-
    datasources:
    - name: Prometheus
      type: prometheus
      type_name: Prometheus
      type_logo_url: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
      access: proxy
      url: "http://prometheus-service:9090"
      org_id: 1
      is_default: true
      read_only: false
